"""The code-file gate: turn a Capability Tag into a typed Python module.

    open-mhs export examples/robotic_arm.mhs --out arm01.py

The generated module is standalone — stdlib only — and exposes one method per channel:
`read_<id>()` for every sensor and actuator, `write_<id>(value)` for every actuator, plus
`snapshot()`, `check()`, and `emergency_stop()`. An agent can import it, write a controller
against it, and leave that controller running with no model in the loop.

The module enforces NOTHING. Every bound lives in its docstrings and in `BOUNDS` for a
controller to read, but every write still goes to the middleware, which refuses anything
outside the envelope exactly as it would for an MCP call. A controller that never reads
the bounds is still safe; it is just refused more often.
"""

from __future__ import annotations

import json
import re
from typing import Any

from open_mhs.server.models import CapabilityTag

PY_TYPES = {
    "number": "float",
    "integer": "int",
    "boolean": "bool",
    "string": "str",
    "vector3": "list[float]",
}


def class_name(device_id: str) -> str:
    parts = re.split(r"[^0-9a-zA-Z]+", device_id)
    name = "".join(p[:1].upper() + p[1:] for p in parts if p)
    if name[:1].isdigit():
        name = "Device" + name
    return name or "Device"


def method_name(channel_id: str) -> str:
    name = re.sub(r"[^0-9a-zA-Z_]", "_", channel_id)
    if name[:1].isdigit():
        name = "_" + name
    return name


def _py_type(channel: Any) -> str:
    if channel.datatype == "enum":
        return "Literal[" + ", ".join(repr(v) for v in channel.enum_values or []) + "]"
    return PY_TYPES[channel.datatype]


def _bound_doc(limit: Any, unit: str | None) -> str:
    u = f" {unit}" if unit else ""
    if limit.allowed_values is not None:
        core = "allowed values: " + ", ".join(repr(v) for v in limit.allowed_values)
    else:
        core = f"inclusive bound [{limit.min}, {limit.max}]{u}"
    extras = []
    if limit.max_rate:
        extras.append(f"max rate {limit.max_rate}{u}/s")
    if limit.max_duration_s:
        extras.append(f"held away from default for at most {limit.max_duration_s} s")
    if limit.conditions:
        extras.append("tighter under some device states (see BOUNDS)")
    extras.append(f"enforced in {limit.enforcement}, on violation: {limit.on_violation}")
    text = core + "; " + "; ".join(extras)
    if limit.rationale:
        why = limit.rationale.rstrip()
        text += f".\n        Why: {why}" + ("" if why.endswith(".") else ".")
    return text


def generate(tag: CapabilityTag) -> str:
    cls = class_name(tag.device_id)
    limits = tag.limit_map
    uses_literal = any(a.datatype == "enum" for a in tag.actuators) or any(
        s.datatype == "enum" for s in tag.sensors
    )

    bounds = {
        limit.target: json.loads(limit.model_dump_json(exclude_none=True))
        for limit in tag.safety_limits
    }

    out: list[str] = []
    w = out.append
    w('"""' + f"{tag.name} ({tag.device_id}) - generated by `open-mhs export`.")
    w("")
    w(f"Capability Tag spec {tag.mhs_version}. Device type: {tag.type}.")
    if tag.description:
        w("")
        w(tag.description)
    w("")
    w("This module enforces nothing. Every write is sent to the Open-MHS middleware, which")
    w("checks it against the device's declared safety limits before any byte reaches the")
    w("hardware and refuses anything outside them with `OpenMHSRefused`. The bounds are")
    w("repeated here, in docstrings and in BOUNDS, so a controller can plan inside them;")
    w("they are information, not a second enforcement point.")
    w("")
    w("Configure with OPEN_MHS_URL (default http://127.0.0.1:8000) and OPEN_MHS_AUTH_TOKEN.")
    w('"""')
    w("")
    w("from __future__ import annotations")
    w("")
    w("import json")
    w("import os")
    w("import urllib.error")
    w("import urllib.request")
    w("from typing import Any" + (", Literal" if uses_literal else ""))
    w("")
    w(f"DEVICE_ID = {tag.device_id!r}")
    w(f"MHS_VERSION = {tag.mhs_version!r}")
    w("")
    w("#: The device's declared safety limits, verbatim from its Capability Tag.")
    w("BOUNDS: dict[str, dict[str, Any]] = " + json.dumps(bounds, indent=4))
    w("")
    w("")
    w("class OpenMHSRefused(Exception):")
    w('    """The middleware refused the call. `data` carries the real bound."""')
    w("")
    w("    def __init__(self, error: dict[str, Any]) -> None:")
    w('        self.code: int = error.get("code", 0)')
    w('        self.message: str = error.get("message", "")')
    w('        self.data: dict[str, Any] = error.get("data") or {}')
    w('        super().__init__(f"[{self.code}] {self.message}")')
    w("")
    w("")
    w(f"class {cls}:")
    w(f'    """{tag.name}. One method per channel; see the module docstring."""')
    w("")
    w("    def __init__(self, url: str | None = None, token: str | None = None) -> None:")
    w('        self.url = (url or os.getenv("OPEN_MHS_URL") or "http://127.0.0.1:8000").rstrip("/")')
    w('        self.token = token or os.getenv("OPEN_MHS_AUTH_TOKEN") or ""')
    w("")
    w("    # --- transport ---")
    w("")
    w("    def _post(self, body: dict[str, Any]) -> dict[str, Any]:")
    w('        """One HTTP round trip. Override to route through another client."""')
    w("        req = urllib.request.Request(")
    w('            f"{self.url}/rpc", data=json.dumps(body).encode(),')
    w('            headers={"Content-Type": "application/json",')
    w('                     "Authorization": f"Bearer {self.token}"},')
    w("        )")
    w("        try:")
    w("            with urllib.request.urlopen(req, timeout=30) as resp:")
    w("                return json.load(resp)")
    w("        except urllib.error.HTTPError as exc:")
    w('            raise OpenMHSRefused({"code": exc.code, "message": exc.reason}) from exc')
    w("")
    w("    def _rpc(self, method: str, params: dict[str, Any]) -> Any:")
    w('        payload = self._post({"jsonrpc": "2.0", "id": 1, "method": method, "params": params})')
    w('        if "error" in payload:')
    w('            raise OpenMHSRefused(payload["error"])')
    w('        return payload["result"]')
    w("")
    w("    def _read(self, target: str) -> Any:")
    w('        return self._rpc("mhs.read", {"device_id": DEVICE_ID, "target": target})["value"]')
    w("")
    w("    def _write(self, target: str, value: Any, confirm: bool) -> dict[str, Any]:")
    w('        return self._rpc("mhs.write", {"device_id": DEVICE_ID, "target": target,')
    w('                                       "value": value, "confirm": confirm})')
    w("")
    w("    # --- whole device ---")
    w("")
    w("    def snapshot(self) -> dict[str, Any]:")
    w('        """Every channel of this device in one call: {channel: {"value", "unit"} | {"error"}}."""')
    w('        result = self._rpc("mhs.snapshot", {"device_ids": [DEVICE_ID]})')
    w('        return result["devices"][DEVICE_ID]["channels"]')
    w("")
    w("    def check(self, writes: list[dict[str, Any]]) -> dict[str, Any]:")
    w('        """Dry-run a list of {"target", "value", "confirm"?} against the live envelope.')
    w("        Nothing is transmitted. Returns the middleware's per-item verdicts.\"\"\"")
    w('        items = [{"device_id": DEVICE_ID, **w} for w in writes]')
    w('        return self._rpc("mhs.check", {"writes": items})')
    w("")
    if tag.emergency_stop and tag.emergency_stop.supported:
        safe = tag.emergency_stop.safe_state or {}
        w("    def emergency_stop(self) -> dict[str, Any]:")
        w(f'        """Drive the device to its declared safe state: {safe}."""')
        w('        return self._rpc("mhs.emergency_stop", {"device_id": DEVICE_ID})')
        w("")
    else:
        w("    # This device declares no emergency stop. There is nothing to drive it to.")
        w("")

    w("    # --- sensors (read-only) ---")
    w("")
    for s in tag.sensors:
        w(f"    def read_{method_name(s.id)}(self) -> {_py_type(s)}:")
        doc = s.name or s.id
        if s.unit:
            doc += f", in {s.unit}"
        if s.accuracy is not None:
            doc += f", accuracy {s.accuracy}"
        if s.description:
            doc += f". {s.description}"
        w(f'        """{doc}"""')
        w(f"        return self._read({s.id!r})")
        w("")

    w("    # --- actuators ---")
    w("")
    for a in tag.actuators:
        limit = limits[a.id]
        py = _py_type(a)
        w(f"    def read_{method_name(a.id)}(self) -> {py}:")
        w(f'        """Last commanded {a.name or a.id}' + (f", in {a.unit}" if a.unit else "") + '."""')
        w(f"        return self._read({a.id!r})")
        w("")
        w(f"    def write_{method_name(a.id)}(self, value: {py}, *, confirm: bool = False) -> dict[str, Any]:")
        doc = [f"Command {a.name or a.id}" + (f", in {a.unit}" if a.unit else "") + "."]
        bound_text = _bound_doc(limit, a.unit)
        doc.append(f"        {bound_text}" + ("" if bound_text.endswith(".") else "."))
        if a.write_mode == "relative":
            doc.append("        Relative write: `value` is a delta; the bound applies to the result.")
        if a.requires_confirmation:
            doc.append("        REQUIRES HUMAN CONFIRMATION: refused unless confirm=True after a person approved.")
        if a.feedback_sensor:
            doc.append(f"        Verified against read_{method_name(a.feedback_sensor)}(); a mismatch raises OpenMHSRefused(-32003).")
        doc.append("        Raises OpenMHSRefused(-32001) outside the bound; nothing is transmitted.")
        w('        """' + "\n".join(doc) + '\n        """')
        w(f"        return self._write({a.id!r}, value, confirm)")
        w("")

    w("")
    w("__all__ = [" + ", ".join(repr(n) for n in (cls, "OpenMHSRefused", "BOUNDS", "DEVICE_ID")) + "]")
    w("")
    return "\n".join(out)
