"""Turn a Capability Tag into the reference file an agent reads before touching hardware.

    open-mhs doc examples/robotic_arm.mhs --out DEVICE.md

The tag is the machine-readable contract; this is the same contract in the shape a model
actually consumes — Markdown, in the working directory, next to CLAUDE.md. Nothing here is
authored by hand, so it cannot drift from the tag, and nothing here is consulted for a
safety decision: the middleware reads the tag, not this file.

Every number in the output comes from the tag. If a field is absent, the document says so
rather than filling in a plausible default — an agent that assumes an undeclared bound is
exactly the failure this project exists to prevent.
"""

from __future__ import annotations

from typing import Any

from server.models import Actuator, CapabilityTag, SafetyLimit, Sensor


def _unit(suffix: str | None) -> str:
    return f" {suffix}" if suffix else ""


def _sensor_row(s: Sensor) -> str:
    u = _unit(s.unit)
    detail: list[str] = []
    if s.nominal_range:
        detail.append(f"measures {s.nominal_range.min} to {s.nominal_range.max}{u}")
    if s.enum_values:
        detail.append("one of " + ", ".join(f"`{v}`" for v in s.enum_values))
    if s.accuracy is not None:
        detail.append(f"accuracy ±{s.accuracy}{u}")
    if s.sample_rate_hz:
        detail.append(f"{s.sample_rate_hz} Hz")
    return (
        f"| `{s.id}` | {s.datatype}{u} | {s.name or ''} | "
        f"{'; '.join(detail) or '—'} |"
    )


def _bound_cell(limit: SafetyLimit, unit: str | None) -> str:
    u = _unit(unit)
    if limit.allowed_values is not None:
        return ", ".join(f"`{v}`" for v in limit.allowed_values)
    return f"{limit.min} to {limit.max}{u} inclusive"


def _actuator_row(a: Actuator, limit: SafetyLimit) -> str:
    u = _unit(a.unit)
    notes: list[str] = []
    if a.write_mode == "relative":
        notes.append("relative: value is a delta, the bound applies to the result")
    if limit.max_rate:
        notes.append(f"max rate {limit.max_rate}{u}/s")
    if limit.max_duration_s:
        notes.append(f"returns to default after {limit.max_duration_s} s")
    if a.requires_confirmation:
        notes.append("**needs human confirmation**")
    if limit.conditions:
        notes.append(f"{len(limit.conditions)} conditional bound(s), see below")
    notes.append(f"on violation: {limit.on_violation}")
    return (
        f"| `{a.id}` | {a.datatype}{u} | {_bound_cell(limit, a.unit)} | "
        f"{limit.enforcement} | {'; '.join(notes)} |"
    )


def generate(tag: CapabilityTag, *, url: str = "http://127.0.0.1:8000") -> str:
    out: list[str] = []
    w = out.append
    limits = tag.limit_map

    w(f"# {tag.name}")
    w("")
    w(f"`{tag.device_id}` — {tag.type}. Capability Tag spec {tag.mhs_version}.")
    if tag.vendor or tag.model:
        w("")
        w(f"{tag.vendor or 'unknown vendor'} {tag.model or ''}".strip()
          + (f", firmware {tag.firmware_version}" if tag.firmware_version else ""))
    if tag.description:
        w("")
        w(tag.description)
    w("")
    w("*Generated by `open-mhs doc` from the device's own Capability Tag. Do not edit: "
      "regenerate it. The middleware enforces the tag, never this file.*")
    w("")

    hazard = tag.power.hazard_class if tag.power else None
    if hazard and hazard != "none":
        w(f"> **Hazard class: {hazard}.** A refused command is a refusal, not a suggestion. "
          "Do not attempt to route around a bound.")
        w("")

    w("## Read")
    w("")
    if tag.sensors:
        w("| id | type | name | notes |")
        w("|---|---|---|---|")
        for s in tag.sensors:
            w(_sensor_row(s))
    else:
        w("This device declares no sensors.")
    w("")

    w("## Write")
    w("")
    if tag.actuators:
        w("Every write is checked against the bound below **before any byte reaches the "
          "hardware**. A refused write changes nothing physically and returns the real "
          "bound; use it to correct yourself rather than retrying the same value.")
        w("")
        w("| id | type | bound | enforced in | notes |")
        w("|---|---|---|---|---|")
        for a in tag.actuators:
            w(_actuator_row(a, limits[a.id]))
        w("")
        rationales = [(a.id, limits[a.id].rationale) for a in tag.actuators if limits[a.id].rationale]
        if rationales:
            w("Why these bounds exist:")
            w("")
            for target, why in rationales:
                w(f"- `{target}`: {why}")
            w("")
        conditional = [(a.id, limits[a.id]) for a in tag.actuators if limits[a.id].conditions]
        if conditional:
            w("### Bounds that change with device state")
            w("")
            w("Evaluated in order; the first match wins. A condition can only ever make the "
              "bound tighter, so the base bound above is the worst case.")
            w("")
            for target, limit in conditional:
                for c in limit.conditions or []:
                    lo = c.min if c.min is not None else limit.min
                    hi = c.max if c.max is not None else limit.max
                    line = f"- `{target}` becomes {lo} to {hi} while `{c.when_target}` reads `{c.equals}`"
                    if c.rationale:
                        line += f" — {c.rationale}"
                    w(line)
            w("")
        verified = [(a.id, a.feedback_sensor) for a in tag.actuators if a.feedback_sensor]
        if verified:
            w("### Verification")
            w("")
            w("These writes are checked against a sensor after they land. A mismatch is a "
              "state desync (`-32003`): your model of the world and the world have diverged, "
              "so stop and re-read rather than repeating the command.")
            w("")
            for target, sensor in verified:
                settle = next(a.settle_time_ms for a in tag.actuators if a.id == target)
                after = f" after {settle} ms" if settle else ""
                w(f"- `{target}` → `{sensor}`{after}")
            w("")
    else:
        w("This device is read-only. It has no actuators, so no write can reach it.")
        w("")

    w("## Emergency stop")
    w("")
    estop = tag.emergency_stop
    if estop and estop.supported:
        state = estop.safe_state or {}
        pairs = ", ".join(f"`{k}` = {v}" for k, v in state.items()) or "a device-defined state"
        w(f"Supported. Drives to {pairs}.")
        if estop.max_stop_time_ms is not None:
            w("")
            w(f"Declared worst-case stop time: {estop.max_stop_time_ms} ms.")
        w("")
        w("The stop bypasses the safety limits by design: the safe state is trusted, and a "
          "stop a limit could refuse would not be a stop.")
    else:
        w("**Not supported.** This device declares no safe state, so there is nothing to "
          "drive it to in an emergency. Plan accordingly: prevention is the only control "
          "you have here.")
    w("")

    w("## How to reach it")
    w("")
    w("Three gates, one enforcer. All of them land on the same safety check.")
    w("")
    w("**MCP** — `discover_hardware`, `read_hardware_state`, `write_hardware_state`, "
      "`snapshot_hardware`, `check_hardware_plan`, `emergency_stop_hardware`, "
      "`emergency_stop_all_hardware`.")
    w("")
    w("**Shell**")
    w("")
    w("```bash")
    example_read = (tag.sensors[0].id if tag.sensors else
                    tag.actuators[0].id if tag.actuators else "<channel>")
    w(f"open-mhs read {tag.device_id} {example_read}")
    if tag.actuators:
        a = tag.actuators[0]
        limit = limits[a.id]
        if limit.allowed_values is not None:
            value: Any = limit.allowed_values[0]
        else:
            value = round((limit.min + limit.max) / 2, 3)  # type: ignore[operator]
        flag = " --confirm" if a.requires_confirmation else ""
        w(f"open-mhs write {tag.device_id} {a.id} {value}{flag}")
    w(f"open-mhs snapshot {tag.device_id}")
    if estop and estop.supported:
        w(f"open-mhs estop {tag.device_id}")
    w("```")
    w("")
    w("**Code** — `open-mhs export` writes a typed module with one method per channel:")
    w("")
    w("```bash")
    w(f"open-mhs export <tag>.mhs --out {tag.device_id.replace('-', '_')}.py")
    w("```")
    w("")
    w("A controller written against that module runs with no model in the loop, and is "
      "still checked by the middleware on every write.")
    w("")
    w("## Errors you will see")
    w("")
    w("| code | meaning | what to do |")
    w("|---|---|---|")
    w("| `-32001` | outside a safety limit; nothing was transmitted | read the bound in "
      "`data` and command a legal value |")
    w("| `-32003` | state desync: commanded and observed disagree | stop, re-read, do not "
      "repeat the command |")
    w("| `-32002` | the link or the device failed | device state is unknown, not unchanged |")
    w("| `-32602` | wrong type, unknown channel, or a missing confirmation | fix the call |")
    w("")
    w("Every one of these, and every accepted command, is written to the middleware's "
      "audit log.")
    w("")
    w("## Connect an MCP client")
    w("")
    w("```json")
    w("{")
    w('  "mcpServers": {')
    w('    "open-mhs": {')
    w('      "command": "open-mhs-mcp",')
    w('      "env": {')
    w(f'        "OPEN_MHS_URL": "{url}",')
    w('        "OPEN_MHS_AUTH_TOKEN": "the-token-the-server-was-started-with"')
    w("      }")
    w("    }")
    w("  }")
    w("}")
    w("```")
    w("")
    return "\n".join(out)
